# Generated by Django 4.2.5 on 2023-09-18 02:09

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audioFile',
            field=models.FileField(upload_to='api/files/audio_files', validators=[api.validators.audioValidator]),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='api/files/images'),
        ),
    ]
